### ISSUE TITLE
Respect des Best Practice™

### ISSUE THREAD

**Issue by halflings** [TurpIF/pdc1#1]
Dans le cadre de ce projet SOA, il faudrait essayer de maximiser la cohésion intra-modulaire du business process ainsi que la planification en strates de l'urbanisation du SI métier; Il faudrait donc maximiser la synergie B2B via un PAQ couvrant le GPU du PHTUD via un CdC voir un MdD en formalisme EML.

**Comment by jmcomets** [comment]
Bien vu ! D'ailleurs, pour découpler correctement les couches services et métier, des DA seront nécéssaires pour garantir la pertinence des DSD. Par la suite les DSM et DSOM devront détailler le DICIHM, toujours en suivant la norme ISO-2120392 ou, en cas d'incomplétude, la norme ISO-X-039841.

**Comment by Vongo** [comment]
Mais, euh... Non ? 
On 18 Jun 2015 4:30 pm, Jean-Marie Comets notifications@github.com wrote:Closed #1.
